-- ===========================================================================
-- Trueward Guru — complete schema
--
-- The whole database in one file. Run it in the Supabase SQL editor; run it
-- again whenever this file changes. It converges an existing database to this
-- state rather than rebuilding one, so it is safe on a database with data in
-- it: tables and columns are added if missing, functions and policies are
-- replaced, and nothing that holds rows is dropped.
--
-- Ordering matters, and is the reason this exists. Applied as separate
-- migrations, running an older file after a newer one silently reverted
-- policies the newer one had tightened — the same policy name recreated with
-- looser wording. One file cannot be applied out of order.
--
-- ---------------------------------------------------------------------------
-- Authorization is entirely RLS
--
-- No query in the app filters by team by hand. If a policy here is wrong the
-- app leaks; if it is right, a forgotten `.eq("team_id", …)` in application
-- code is harmless. That is the whole reason for pushing scoping into the
-- database rather than the query layer.
--
-- Roles are compared as text throughout. Postgres refuses to *use* an enum
-- value in the same transaction that added it, and the SQL editor runs this
-- file as one transaction — so naming 'resume_builder'::user_role in a policy
-- would fail on any database that didn't already have that value.
-- ===========================================================================

create extension if not exists "pgcrypto";

-- ===========================================================================
-- Vocabulary
-- ===========================================================================

do $$
begin
  -- Created without resume_builder and extended below, rather than listing all
  -- four here. Enum ordering is part of the type, and a database built from
  -- this file should sort roles the same way as one that grew through the
  -- earlier migrations — where resume_builder was appended last.
  if to_regtype('public.user_role') is null then
    create type user_role as enum ('super_admin', 'admin', 'bidder');
  end if;

  if to_regtype('public.application_status') is null then
    create type application_status as enum
      ('applied', 'viewed', 'interviewing', 'offer', 'rejected');
  end if;

  -- Billing state of an application, independent of its status.
  if to_regtype('public.billing_status') is null then
    create type billing_status as enum ('unbillable', 'unbilled', 'billed');
  end if;
end
$$;

-- For databases created before the role existed.
alter type user_role add value if not exists 'resume_builder';

-- ===========================================================================
-- Tables
-- ===========================================================================

-- --------------------------------------------------------------------------
-- Users
--
-- auth.users holds credentials; this table holds the app's view of a person.
-- They are 1:1 and share a primary key, so `auth.uid()` joins directly here.
-- --------------------------------------------------------------------------

create table if not exists app_user (
  id            uuid primary key references auth.users (id) on delete cascade,
  email         text not null,
  name          text,
  -- Least privilege by default: a new account must never become an admin
  -- because someone forgot to pass a role.
  role          user_role not null default 'bidder',
  -- Which account created this one. This is what lets an admin manage the
  -- people they added and nobody else's. SET NULL rather than cascade:
  -- removing an admin must not delete their team's logins as a side effect.
  created_by_id uuid references app_user (id) on delete set null,
  created_at    timestamptz not null default now()
);

-- Which resume styles this account may use. Null means "the default for the
-- role" — see src/lib/style-access.ts. An empty array would mean "none", which
-- would leave the account unable to render anything.
alter table app_user
  add column if not exists allowed_templates text[],
  add column if not exists allowed_accents   text[];

create index if not exists app_user_created_by_idx on app_user (created_by_id);

-- --------------------------------------------------------------------------
-- Candidate profiles
--
-- The stable half of a resume: who someone is, where they worked, what they
-- studied. Set once, never regenerated by a model.
--
-- The structured columns are the source of truth. `profile` is a *derived*
-- render payload — the profile half of a resume document, built from those
-- columns by buildProfileDocument() in src/lib/profile.ts. Two writers of the
-- same facts drift; one writer and one reader cannot.
-- --------------------------------------------------------------------------

create table if not exists candidate_profile (
  id            uuid primary key default gen_random_uuid(),
  full_name     text not null,
  email         text,
  profile       jsonb not null,
  team_id       uuid not null references app_user (id) on delete cascade,
  created_by    uuid references app_user (id) on delete set null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

alter table candidate_profile
  add column if not exists phone         text,
  add column if not exists address       text,
  add column if not exists city          text,
  add column if not exists state         text,
  add column if not exists postal_code   text,
  add column if not exists country       text,
  add column if not exists birthday      date,
  add column if not exists github_url    text,
  add column if not exists linkedin_url  text,
  -- pgp_sym_encrypt output. bytea, not text: storing ciphertext as text invites
  -- an encoding round trip that silently corrupts it.
  add column if not exists ssn_encrypted bytea;

-- Superseded: `label` and `headline` by full_name, `bidder_visible` by
-- profile_assignment.
alter table candidate_profile
  drop column if exists label,
  drop column if exists headline,
  drop column if exists bidder_visible;

create index if not exists candidate_profile_team_idx on candidate_profile (team_id);

-- --------------------------------------------------------------------------
-- Profile assignments
--
-- Which bidders may work with which candidates. Without a row here a bidder
-- sees no profile at all — assignment is opt-in, so a new candidate is private
-- to the admins until deliberately routed.
-- --------------------------------------------------------------------------

create table if not exists profile_assignment (
  id          uuid primary key default gen_random_uuid(),
  profile_id  uuid not null references candidate_profile (id) on delete cascade,
  user_id     uuid not null references app_user (id) on delete cascade,
  team_id     uuid not null references app_user (id) on delete cascade,
  assigned_by uuid references app_user (id) on delete set null,
  created_at  timestamptz not null default now(),
  -- Assigning twice is a no-op, not a second row.
  unique (profile_id, user_id)
);

create index if not exists profile_assignment_user_idx on profile_assignment (user_id);
create index if not exists profile_assignment_team_idx on profile_assignment (team_id);

-- --------------------------------------------------------------------------
-- Profile attachments — photos and supporting documents
-- --------------------------------------------------------------------------

create table if not exists profile_attachment (
  id         uuid primary key default gen_random_uuid(),
  profile_id uuid not null references candidate_profile (id) on delete cascade,
  label      text not null,
  file_key   text not null,
  file_url   text not null,
  file_name  text,
  file_type  text,
  file_size  integer,
  team_id    uuid not null references app_user (id) on delete cascade,
  created_by uuid references app_user (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists profile_attachment_profile_idx
  on profile_attachment (profile_id);

-- --------------------------------------------------------------------------
-- Resume documents
--
-- The regenerated half: positioning for one job. `content` is JSONB validated
-- by contentSchema, and its experiences reference candidate_profile
-- employments by id. That reference is checked in the zod schema on the way in,
-- which is what makes an invented employer a validation failure rather than a
-- rendered PDF.
-- --------------------------------------------------------------------------

create table if not exists resume_document (
  id         uuid primary key default gen_random_uuid(),
  title      text not null,
  profile_id uuid not null references candidate_profile (id) on delete cascade,
  content    jsonb not null,
  template   text not null default 'classic',
  -- Font scale, header fields, accent — anything the PDF renderer reads that is
  -- presentation rather than content.
  style      jsonb not null default '{}'::jsonb,
  team_id    uuid not null references app_user (id) on delete cascade,
  created_by uuid references app_user (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists resume_document_team_idx on resume_document (team_id);
create index if not exists resume_document_profile_idx on resume_document (profile_id);

-- --------------------------------------------------------------------------
-- Blocked companies — never to receive an application, from any profile
-- --------------------------------------------------------------------------

create table if not exists blocked_company (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  -- Lowercased, punctuation stripped, legal suffixes removed. Matching happens
  -- on this column, so the unique index actually prevents "Acme, Inc." and
  -- "acme inc" coexisting.
  normalized_name text not null,
  team_id         uuid not null references app_user (id) on delete cascade,
  created_by      uuid references app_user (id) on delete set null,
  created_at      timestamptz not null default now()
);

create unique index if not exists blocked_company_team_name_uidx
  on blocked_company (team_id, normalized_name);

-- --------------------------------------------------------------------------
-- Applications
--
-- Uploaded resumes live in UploadThing; `resume_key` is their handle, kept so
-- deleting a row can delete the file rather than leaking storage.
-- --------------------------------------------------------------------------

create table if not exists application (
  id                 uuid primary key default gen_random_uuid(),
  title              text not null,
  company            text not null,
  job_url            text not null,
  status             application_status not null default 'applied',
  billing            billing_status not null default 'unbilled',
  notes              text,
  resume_document_id uuid references resume_document (id) on delete set null,
  profile_id         uuid references candidate_profile (id) on delete set null,
  applied_at         timestamptz not null default now(),
  team_id            uuid not null references app_user (id) on delete cascade,
  created_by         uuid references app_user (id) on delete set null,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

alter table application
  add column if not exists resume_key  text,
  add column if not exists resume_url  text,
  add column if not exists resume_name text;

-- The shared resume library is gone: a resume belongs to the application it was
-- sent with, which is how anyone reading the grid thinks about it.
alter table application drop column if exists resume_file_id;
drop table if exists resume_file;

create index if not exists application_team_idx on application (team_id);
create index if not exists application_created_by_idx on application (created_by);
create index if not exists application_status_idx on application (status);
create index if not exists application_applied_at_idx on application (applied_at desc);
create index if not exists application_profile_idx on application (profile_id);
-- Duplicate detection matches on lower(company), so the index must too — a
-- plain index on company would go unused by that lookup.
create index if not exists application_company_lower_idx on application (lower(company));

-- --------------------------------------------------------------------------
-- SSN access log
--
-- Every reveal is recorded. An encrypted column whose plaintext can be pulled
-- without trace is only half a control.
-- --------------------------------------------------------------------------

create table if not exists ssn_access_log (
  id          uuid primary key default gen_random_uuid(),
  profile_id  uuid not null references candidate_profile (id) on delete cascade,
  actor_id    uuid references app_user (id) on delete set null,
  team_id     uuid not null references app_user (id) on delete cascade,
  revealed_at timestamptz not null default now()
);

create index if not exists ssn_access_log_profile_idx
  on ssn_access_log (profile_id, revealed_at desc);

-- ===========================================================================
-- Identity and scope
-- ===========================================================================

/**
 * Mirror every auth signup into app_user.
 *
 * SECURITY DEFINER because the trigger runs as the *signing-up* user, who has
 * no rights on app_user yet — the row it needs to insert is the very row that
 * would grant them.
 */
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.app_user (id, email, name)
  values (new.id, new.email, nullif(new.raw_user_meta_data ->> 'name', ''));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

/**
 * The caller's role.
 *
 * SECURITY DEFINER so it can read app_user without re-entering that table's own
 * policies, which would recurse infinitely. STABLE so Postgres evaluates it
 * once per statement rather than once per row.
 */
create or replace function public.app_role()
returns user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from app_user where id = auth.uid()
$$;

/**
 * The team the caller belongs to, identified by an admin's id.
 *
 *   admin                    their own id
 *   bidder, resume_builder   the admin who created them
 *   super_admin              none — they manage accounts, not records
 *
 * Listing the roles it knows and returning null for the rest is a trap worth
 * naming: every policy starts with `team_id = app_team_id()`, and that against
 * null is not false but *unknown*, so it matches nothing. An account whose role
 * is missing here can read nothing and write nothing, with no error saying why.
 */
create or replace function public.app_team_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select case
    when u.role::text = 'admin' then u.id
    when u.role::text in ('bidder', 'resume_builder') then u.created_by_id
    else null
  end
  from app_user u
  where u.id = auth.uid()
$$;

/**
 * The privileged roles.
 *
 * A positive list rather than "not a bidder". That phrasing was the same thing
 * while bidder was the only unprivileged role, and stopped being so the moment
 * a second one existed — every check written that way would hand a new role
 * admin rights by default.
 */
create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select app_role()::text in ('admin', 'super_admin')
$$;

create or replace function public.is_builder()
returns boolean
language sql
stable
as $$
  select app_role()::text = 'resume_builder'
$$;

/**
 * Which profiles the caller may work with.
 *
 *   admin           every profile on the team
 *   resume_builder  only the ones they created
 *   bidder          only the ones assigned to them
 *
 * SECURITY DEFINER so candidate_profile's policy can consult
 * profile_assignment without that table's policy re-entering
 * candidate_profile — the two reference each other.
 */
create or replace function public.can_use_profile(target uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select case
    when is_admin() then true
    when is_builder() then exists (
      select 1 from candidate_profile
      where id = target and created_by = auth.uid()
    )
    else exists (
      select 1 from profile_assignment
      where profile_id = target and user_id = auth.uid()
    )
  end
$$;

-- ===========================================================================
-- Bookkeeping
-- ===========================================================================

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists candidate_profile_touch on candidate_profile;
create trigger candidate_profile_touch before update on candidate_profile
  for each row execute function public.touch_updated_at();

drop trigger if exists resume_document_touch on resume_document;
create trigger resume_document_touch before update on resume_document
  for each row execute function public.touch_updated_at();

drop trigger if exists application_touch on application;
create trigger application_touch before update on application
  for each row execute function public.touch_updated_at();

-- ===========================================================================
-- Social Security numbers
--
-- The key never lives in the database. It is passed in per call from
-- APP_ENCRYPTION_KEY, held only in the server environment, so a dump of
-- candidate_profile yields ciphertext and nothing else. Losing it means losing
-- every stored SSN — that is the intended trade.
-- ===========================================================================

create or replace function public.encrypt_ssn(plain text, key text)
returns bytea
language sql
immutable
as $$
  select case
    when plain is null or btrim(plain) = '' then null
    -- Digits only: "123-45-6789" and "123456789" must not encrypt to two
    -- different ciphertexts for the same person.
    else pgp_sym_encrypt(regexp_replace(plain, '\D', '', 'g'), key)
  end
$$;

create or replace function public.decrypt_ssn(cipher bytea, key text)
returns text
language plpgsql
immutable
as $$
begin
  if cipher is null then
    return null;
  end if;
  return pgp_sym_decrypt(cipher, key);
exception
  -- A wrong key raises. Surfacing that as null rather than an error keeps the
  -- failure from leaking whether a given row *has* an SSN.
  when others then
    return null;
end;
$$;

/**
 * Read and write the ciphertext without the key or the plaintext crossing the
 * client boundary.
 *
 * Called only from the service-role client, and only after
 * src/app/dashboard/profiles/ssn-actions.ts has checked the caller is an admin
 * *and* that the row is visible to them through RLS. Service role bypasses
 * policies, so these are exactly as safe as those checks — which is why they
 * are revoked from public below.
 */
create or replace function public.reveal_ssn(target uuid, key text)
returns text
language sql
stable
as $$
  select decrypt_ssn(ssn_encrypted, key) from candidate_profile where id = target
$$;

create or replace function public.store_ssn(target uuid, plain text, key text)
returns void
language sql
as $$
  update candidate_profile
     set ssn_encrypted = encrypt_ssn(plain, key)
   where id = target
$$;

-- PostgREST exposes public functions to any authenticated caller by default.
-- These must not be reachable that way — anon or authenticated could otherwise
-- call reveal_ssn with a guessed key and skip every check above.
revoke all on function public.reveal_ssn(uuid, text) from public;
revoke all on function public.store_ssn(uuid, text, text) from public;
revoke all on function public.encrypt_ssn(text, text) from public;
revoke all on function public.decrypt_ssn(bytea, text) from public;

-- ===========================================================================
-- Duplicate applications
-- ===========================================================================

/**
 * A company's comparison key.
 *
 * Lowercased, punctuation collapsed, trailing legal suffixes removed — so
 * "Globex", "globex inc" and "Globex, Inc." are one employer. Without the
 * suffix step the guard is defeated by typing the name a slightly different
 * way, which is exactly what someone re-applying would do.
 *
 * Must stay in step with normalizeCompany() in src/lib/status.ts, which lets
 * the UI warn before a write this would refuse.
 */
create or replace function public.normalize_company(name text)
returns text
language sql
immutable
as $$
  with squashed as (
    select btrim(regexp_replace(lower(coalesce(name, '')), '[^a-z0-9]+', ' ', 'g')) as value
  ),
  trimmed as (
    select
      value,
      btrim(regexp_replace(
        value,
        '(\s+(inc|incorporated|llc|llp|lp|ltd|limited|corp|corporation|co|company|holdings|group|gmbh|plc|ag|sa|nv|bv|ab|oy|as|pty|srl|spa))+$',
        '', 'g'
      )) as stripped
    from squashed
  )
  select case when stripped = '' then value else stripped end from trimmed
$$;

create index if not exists application_company_normalized_idx
  on application (profile_id, normalize_company(company), applied_at desc);

/** How many days a company is closed to a profile after an application. */
create or replace function public.application_cooldown_days()
returns integer
language sql
immutable
as $$ select 14 $$;

/**
 * One profile, one company, 14 days.
 *
 * A trigger rather than a check in the app: the anon key reaches Postgres
 * directly, and the duplicate this catches is usually a *teammate's* row, which
 * client code often cannot see at all.
 *
 * SECURITY DEFINER for that second reason — a bidder cannot read a teammate's
 * application, and with their visibility the duplicate would be invisible here.
 */
create or replace function public.enforce_application_cooldown()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  clash record;
  window_days integer := application_cooldown_days();
begin
  -- Rows with no profile predate this rule and have nothing to clash against.
  if new.profile_id is null then
    return new;
  end if;

  select a.id, a.company, a.applied_at, u.name, u.email
    into clash
    from application a
    left join app_user u on u.id = a.created_by
   where a.profile_id = new.profile_id
     and a.team_id = new.team_id
     and normalize_company(a.company) = normalize_company(new.company)
     -- Measured between the two applications rather than from now(), so the
     -- rule means "not twice within 14 days of each other". Anchoring on now()
     -- would make the same pair legal or illegal depending on when the row
     -- happened to be typed, and would refuse a correctly backdated entry.
     and a.applied_at > new.applied_at - make_interval(days => window_days)
     and a.applied_at < new.applied_at + make_interval(days => window_days)
     and a.id is distinct from new.id
   order by a.applied_at desc
   limit 1;

  if found then
    raise exception using
      errcode = 'check_violation',
      message = format(
        '%s was already applied to for this profile on %s by %s. It reopens on %s.',
        clash.company,
        to_char(clash.applied_at, 'Mon DD, YYYY'),
        coalesce(clash.name, clash.email, 'a teammate'),
        to_char(clash.applied_at + make_interval(days => window_days), 'Mon DD, YYYY')
      );
  end if;

  return new;
end;
$$;

drop trigger if exists application_cooldown on application;
-- Fires on update too: moving an application's date or company could otherwise
-- walk around the rule its insert was refused for.
create trigger application_cooldown
  before insert or update of profile_id, company, applied_at on application
  for each row execute function public.enforce_application_cooldown();

/**
 * Billing is an admin decision — a bidder records the application, an admin
 * decides what it is worth.
 *
 * A trigger because RLS is row-level: a policy can say whether a row may be
 * updated at all, not which of its columns may change. Postgres column
 * privileges are granted to *database* roles, and every signed-in caller shares
 * the one `authenticated` role.
 */
create or replace function public.enforce_billing_authority()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if is_admin() then
    return new;
  end if;

  if tg_op = 'INSERT' then
    -- Rejecting rather than silently coercing, so a client sending something
    -- else finds out it was ignored.
    if new.billing is distinct from 'unbilled'::billing_status then
      raise exception using
        errcode = 'insufficient_privilege',
        message = 'Only an admin can set billing status. New applications start as unbilled.';
    end if;
    return new;
  end if;

  if new.billing is distinct from old.billing then
    raise exception using
      errcode = 'insufficient_privilege',
      message = format(
        'Only an admin can change billing status (tried %s → %s).',
        old.billing, new.billing
      );
  end if;

  return new;
end;
$$;

drop trigger if exists application_billing_authority on application;
create trigger application_billing_authority
  before insert or update on application
  for each row execute function public.enforce_billing_authority();

/**
 * The cooling-off list — one row per (profile, company) still inside the
 * window.
 *
 * Derived, not stored. A table of "currently blocked" pairs would need expiring
 * and would be one more thing able to disagree with the applications it is
 * computed from. security_invoker, so the caller's own policies decide what
 * they see.
 */
drop view if exists application_cooldown;
create view application_cooldown
with (security_invoker = true) as
  select distinct on (a.profile_id, normalize_company(a.company))
    a.profile_id,
    p.full_name as profile_name,
    a.company,
    a.applied_at,
    a.applied_at + make_interval(days => application_cooldown_days()) as reopens_at,
    a.created_by,
    a.team_id
  from application a
  join candidate_profile p on p.id = a.profile_id
  where a.profile_id is not null
    and a.applied_at > now() - make_interval(days => application_cooldown_days())
  order by a.profile_id, normalize_company(a.company), a.applied_at desc;

-- ===========================================================================
-- Row level security
--
-- Shape shared by every record table:
--   read   — the row is in my team, and my role may reach it
--   write  — same, plus the row must be stamped with my team and my id
--
-- The WITH CHECK clauses are what stop a client inserting into another team by
-- posting a different team_id: the anon key reaches Postgres directly, so
-- anything not asserted here is not enforced anywhere.
-- ===========================================================================

alter table app_user           enable row level security;
alter table candidate_profile  enable row level security;
alter table profile_assignment enable row level security;
alter table profile_attachment enable row level security;
alter table resume_document    enable row level security;
alter table blocked_company    enable row level security;
alter table application        enable row level security;
alter table ssn_access_log     enable row level security;

-- --- app_user -------------------------------------------------------------

-- Always your own row: the app reads it on every request to learn your role,
-- and the policies below would deadlock on themselves without it.
drop policy if exists app_user_self_select on app_user;
create policy app_user_self_select on app_user
  for select using (id = auth.uid());

drop policy if exists app_user_team_select on app_user;
create policy app_user_team_select on app_user
  for select using (
    app_role()::text = 'super_admin'
    or created_by_id = auth.uid()
    or id = app_team_id()
  );

drop policy if exists app_user_self_update on app_user;
create policy app_user_self_update on app_user
  for update using (id = auth.uid()) with check (
    id = auth.uid()
    -- Your own row, but not your own role: self-promotion would make the
    -- hierarchy decorative. Compared against app_role() rather than a subquery
    -- on app_user, which would re-enter this table's policies and recurse.
    and role = app_role()
  );

-- --- candidate_profile ----------------------------------------------------

drop policy if exists candidate_profile_select on candidate_profile;
create policy candidate_profile_select on candidate_profile
  for select using (team_id = app_team_id() and can_use_profile(id));

drop policy if exists candidate_profile_insert on candidate_profile;
create policy candidate_profile_insert on candidate_profile
  for insert with check (
    team_id = app_team_id()
    and created_by = auth.uid()
    and (is_admin() or is_builder())
  );

-- A builder edits their own; an admin edits anything on the team. A bidder
-- edits nothing — they write resume content, not someone's identity.
drop policy if exists candidate_profile_update on candidate_profile;
create policy candidate_profile_update on candidate_profile
  for update using (
    team_id = app_team_id()
    and (is_admin() or (is_builder() and created_by = auth.uid()))
  ) with check (team_id = app_team_id());

drop policy if exists candidate_profile_delete on candidate_profile;
create policy candidate_profile_delete on candidate_profile
  for delete using (
    team_id = app_team_id()
    and (is_admin() or (is_builder() and created_by = auth.uid()))
  );

-- --- profile_assignment ---------------------------------------------------

-- A bidder may read their own assignments — that is how the UI knows what to
-- offer — but only an admin may create or remove one.
drop policy if exists profile_assignment_select on profile_assignment;
create policy profile_assignment_select on profile_assignment
  for select using (
    team_id = app_team_id() and (is_admin() or user_id = auth.uid())
  );

drop policy if exists profile_assignment_insert on profile_assignment;
create policy profile_assignment_insert on profile_assignment
  for insert with check (
    team_id = app_team_id() and is_admin() and assigned_by = auth.uid()
  );

drop policy if exists profile_assignment_delete on profile_assignment;
create policy profile_assignment_delete on profile_assignment
  for delete using (team_id = app_team_id() and is_admin());

-- --- profile_attachment ---------------------------------------------------

drop policy if exists profile_attachment_select on profile_attachment;
create policy profile_attachment_select on profile_attachment
  for select using (team_id = app_team_id() and can_use_profile(profile_id));

drop policy if exists profile_attachment_insert on profile_attachment;
create policy profile_attachment_insert on profile_attachment
  for insert with check (
    team_id = app_team_id()
    and created_by = auth.uid()
    and can_use_profile(profile_id)
  );

drop policy if exists profile_attachment_delete on profile_attachment;
create policy profile_attachment_delete on profile_attachment
  for delete using (team_id = app_team_id() and can_use_profile(profile_id));

-- --- resume_document ------------------------------------------------------
-- Follows the profile: you may write a resume for a candidate you may work
-- with, and change one you wrote.

drop policy if exists resume_document_select on resume_document;
create policy resume_document_select on resume_document
  for select using (team_id = app_team_id() and can_use_profile(profile_id));

drop policy if exists resume_document_insert on resume_document;
create policy resume_document_insert on resume_document
  for insert with check (
    team_id = app_team_id()
    and created_by = auth.uid()
    and can_use_profile(profile_id)
  );

drop policy if exists resume_document_update on resume_document;
create policy resume_document_update on resume_document
  for update using (
    team_id = app_team_id()
    and (is_admin() or created_by = auth.uid())
    and can_use_profile(profile_id)
  ) with check (team_id = app_team_id());

drop policy if exists resume_document_delete on resume_document;
create policy resume_document_delete on resume_document
  for delete using (
    team_id = app_team_id()
    and (is_admin() or created_by = auth.uid())
    and can_use_profile(profile_id)
  );

-- --- blocked_company ------------------------------------------------------
-- Readable by the whole team — a bidder must be able to check the list before
-- applying, which is the only reason it exists. Edited by admins.

drop policy if exists blocked_company_select on blocked_company;
create policy blocked_company_select on blocked_company
  for select using (team_id = app_team_id());

drop policy if exists blocked_company_insert on blocked_company;
create policy blocked_company_insert on blocked_company
  for insert with check (
    team_id = app_team_id() and is_admin() and created_by = auth.uid()
  );

drop policy if exists blocked_company_delete on blocked_company;
create policy blocked_company_delete on blocked_company
  for delete using (team_id = app_team_id() and is_admin());

-- --- application ----------------------------------------------------------
--
-- Sharing a candidate means sharing their history: two people working the same
-- profile need to see where it has already been sent, or they duplicate each
-- other's work. Acting on a record stays with whoever recorded it.
--
-- A resume_builder has no part in the tracker at all.

drop policy if exists application_select on application;
create policy application_select on application
  for select using (
    team_id = app_team_id()
    and not is_builder()
    and (
      is_admin()                      -- admins see the whole team
      or created_by = auth.uid()      -- your own rows, profile or not
      or can_use_profile(profile_id)  -- rows for a profile you're assigned
    )
  );

drop policy if exists application_insert on application;
create policy application_insert on application
  for insert with check (
    team_id = app_team_id() and created_by = auth.uid() and not is_builder()
  );

drop policy if exists application_update on application;
create policy application_update on application
  for update using (
    team_id = app_team_id()
    and not is_builder()
    and (is_admin() or created_by = auth.uid())
  ) with check (team_id = app_team_id());

drop policy if exists application_delete on application;
create policy application_delete on application
  for delete using (
    team_id = app_team_id()
    and not is_builder()
    and (is_admin() or created_by = auth.uid())
  );

-- --- ssn_access_log -------------------------------------------------------
-- Admins audit; nobody else reveals an SSN, so nobody else has anything to
-- read. Append-only on purpose: no update or delete policy exists, so the trail
-- cannot be edited from the app at all.

drop policy if exists ssn_access_log_select on ssn_access_log;
create policy ssn_access_log_select on ssn_access_log
  for select using (team_id = app_team_id() and is_admin());

drop policy if exists ssn_access_log_insert on ssn_access_log;
create policy ssn_access_log_insert on ssn_access_log
  for insert with check (
    team_id = app_team_id() and actor_id = auth.uid()
  );

-- ===========================================================================
-- Note on file storage
--
-- Uploaded bytes live in UploadThing, not in Supabase Storage, so there is no
-- bucket or storage.objects policy here. Access control for a file is the row
-- that points at it: the row is team-scoped by the policies above, and the app
-- only ever surfaces a URL it read from a row the caller was allowed to select.
--
-- Worth being clear about the limit of that: an UploadThing file URL is a
-- capability, not a session-checked resource. Anyone holding the URL can fetch
-- it. If resumes ever need to be unguessable-and-revocable, move them behind a
-- route handler that re-checks the row before streaming.
-- ===========================================================================
