-- ===========================================================================
-- Application — initial schema
--
-- Two halves that meet at the resume document:
--   * the tracker (applications, resume files, blocked companies), from Bid
--   * the resume builder (candidate profiles, resume documents), from
--     trueward-resume
--
-- Authorization is entirely RLS. No query in the app filters by team by hand;
-- if a policy below is wrong, the app leaks, and if it is right, a forgotten
-- `.eq("team_id", …)` in application code is harmless. That is the whole
-- reason for pushing scoping into the database rather than the query layer.
-- ===========================================================================

create extension if not exists "pgcrypto";

-- --------------------------------------------------------------------------
-- Vocabulary
-- --------------------------------------------------------------------------

create type user_role as enum ('super_admin', 'admin', 'bidder');

create type application_status as enum (
  'applied', 'viewed', 'interviewing', 'offer', 'rejected'
);

-- Billing state of an application, independent of its status.
create type billing_status as enum ('unbillable', 'unbilled', 'billed');

-- --------------------------------------------------------------------------
-- Users
--
-- auth.users holds credentials; this table holds the app's view of a person.
-- They are 1:1 and share a primary key, so `auth.uid()` joins directly here
-- without a lookup table.
-- --------------------------------------------------------------------------

create table app_user (
  id            uuid primary key references auth.users (id) on delete cascade,
  email         text not null,
  name          text,
  -- Least privilege by default: a new account must never become an admin
  -- because someone forgot to pass a role.
  role          user_role not null default 'bidder',
  -- Which account created this one. This is what lets an admin manage the
  -- bidders they added and nobody else's. SET NULL rather than cascade:
  -- removing an admin must not delete their bidders' logins as a side effect.
  created_by_id uuid references app_user (id) on delete set null,
  created_at    timestamptz not null default now()
);


create index app_user_created_by_idx on app_user (created_by_id);

/**
 * Mirror every auth signup into app_user.
 *
 * SECURITY DEFINER because the trigger runs as the *signing-up* user, who has
 * no rights on app_user yet — the row it needs to insert is the very row that
 * would grant them.
 */
create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.app_user (id, email, name)
  values (
    new.id,
    new.email,
    nullif(new.raw_user_meta_data ->> 'name', '')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- --------------------------------------------------------------------------
-- Scope helpers
--
-- Records belong to a *team*, identified by an admin's id:
--   * an admin's team is their own id
--   * a bidder's team is the admin who created them
--   * a super admin has no team — they manage accounts, not records
--
-- Both are SECURITY DEFINER so they can read app_user without re-entering
-- app_user's own RLS policies, which would recurse infinitely. Both are STABLE
-- so Postgres evaluates them once per statement rather than once per row.
-- --------------------------------------------------------------------------

create function public.app_role()
returns user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from app_user where id = auth.uid()
$$;

create function public.app_team_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select case u.role
    when 'admin'  then u.id
    when 'bidder' then u.created_by_id
    else null            -- super_admin: owns no records
  end
  from app_user u
  where u.id = auth.uid()
$$;

-- --------------------------------------------------------------------------
-- Candidate profiles
--
-- The stable half of a resume: who you are, where you worked, what you
-- studied. Set once, never regenerated by a model.
--
-- `profile` is JSONB validated by profileSchema in src/lib/document/schema.ts
-- rather than a column per field. Employments are a nested, ordered, id-bearing
-- list that is only ever read as a whole document — normalizing it would buy
-- queries nobody runs and cost a join on every render. The name/email columns
-- alongside it are denormalized purely so list views can render without
-- parsing every document.
-- --------------------------------------------------------------------------

create table candidate_profile (
  id             uuid primary key default gen_random_uuid(),
  label          text not null,
  full_name      text not null,
  email          text,
  headline       text,
  profile        jsonb not null,
  -- Whether bidders on the team may use this profile. Admins always see all.
  bidder_visible boolean not null default true,
  team_id        uuid not null references app_user (id) on delete cascade,
  created_by     uuid references app_user (id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index candidate_profile_team_idx on candidate_profile (team_id);

-- --------------------------------------------------------------------------
-- Resume documents
--
-- The regenerated half: positioning for one job. `content` is JSONB validated
-- by contentSchema, and its experiences reference candidate_profile
-- employments by id. That reference is checked in the zod schema on the way
-- in, which is what makes an invented employer a validation failure rather
-- than a rendered PDF.
-- --------------------------------------------------------------------------

create table resume_document (
  id            uuid primary key default gen_random_uuid(),
  title         text not null,
  profile_id    uuid not null references candidate_profile (id) on delete cascade,
  content       jsonb not null,
  template      text not null default 'classic',
  -- Font scale, header position, accent — anything the PDF renderer reads that
  -- is presentation rather than content.
  style         jsonb not null default '{}'::jsonb,
  team_id       uuid not null references app_user (id) on delete cascade,
  created_by    uuid references app_user (id) on delete set null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index resume_document_team_idx on resume_document (team_id);
create index resume_document_profile_idx on resume_document (profile_id);

-- --------------------------------------------------------------------------
-- Resume files
--
-- An uploaded CV or an external link. Uploads go to UploadThing rather than
-- through this app: the browser posts the bytes straight to their endpoint, so
-- no request body ever crosses a serverless function and there is no 4.5 MB
-- Vercel body limit to design around.
--
-- `file_key` is UploadThing's handle — the value their API needs to delete the
-- object. Keeping it is what makes deleting a row able to delete the file too,
-- rather than leaking storage on every removal.
-- --------------------------------------------------------------------------

create table resume_file (
  id         uuid primary key default gen_random_uuid(),
  label      text not null,
  -- Set when the resume is an external link; null for uploads.
  url        text,
  file_key   text,
  file_url   text,
  file_name  text,
  file_type  text,
  file_size  integer,
  team_id    uuid not null references app_user (id) on delete cascade,
  created_by uuid references app_user (id) on delete set null,
  created_at timestamptz not null default now(),

  -- A row is one or the other, never neither: a resume with no link and no
  -- file is a dead reference that would render as a broken button.
  constraint resume_file_has_source check (
    url is not null or file_key is not null
  )
);

create index resume_file_team_idx on resume_file (team_id);

-- --------------------------------------------------------------------------
-- Blocked companies
--
-- Companies that must never receive an application.
-- --------------------------------------------------------------------------

create table blocked_company (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  -- Lowercased, punctuation-stripped. Matching happens on this column, so the
  -- unique index below actually prevents "Acme, Inc." and "acme inc" coexisting.
  normalized_name text not null,
  team_id         uuid not null references app_user (id) on delete cascade,
  created_by      uuid references app_user (id) on delete set null,
  created_at      timestamptz not null default now()
);

create unique index blocked_company_team_name_uidx
  on blocked_company (team_id, normalized_name);

-- --------------------------------------------------------------------------
-- Applications
-- --------------------------------------------------------------------------

create table application (
  id                 uuid primary key default gen_random_uuid(),
  title              text not null,
  company            text not null,
  job_url            text not null,
  status             application_status not null default 'applied',
  billing            billing_status not null default 'unbilled',
  notes              text,
  resume_file_id     uuid references resume_file (id) on delete set null,
  resume_document_id uuid references resume_document (id) on delete set null,
  profile_id         uuid references candidate_profile (id) on delete set null,
  applied_at         timestamptz not null default now(),
  team_id            uuid not null references app_user (id) on delete cascade,
  created_by         uuid references app_user (id) on delete set null,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index application_team_idx on application (team_id);
create index application_created_by_idx on application (created_by);
create index application_status_idx on application (status);
create index application_applied_at_idx on application (applied_at desc);
-- Duplicate detection matches on lower(company), so the index must too — a
-- plain index on company would go unused by that lookup.
create index application_company_lower_idx on application (lower(company));

-- --------------------------------------------------------------------------
-- updated_at
-- --------------------------------------------------------------------------

create function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger candidate_profile_touch before update on candidate_profile
  for each row execute function public.touch_updated_at();
create trigger resume_document_touch before update on resume_document
  for each row execute function public.touch_updated_at();
create trigger application_touch before update on application
  for each row execute function public.touch_updated_at();

-- ===========================================================================
-- Row level security
--
-- Shape shared by every record table:
--   read   — the row is in my team, and if I'm a bidder, I recorded it
--   write  — same, plus the row must be stamped with my team and my id
--
-- The WITH CHECK clauses are what stop a client from inserting into another
-- team by simply posting a different team_id: the anon key reaches Postgres
-- directly, so anything not asserted here is not enforced anywhere.
-- ===========================================================================

alter table app_user          enable row level security;
alter table candidate_profile enable row level security;
alter table resume_document   enable row level security;
alter table resume_file       enable row level security;
alter table blocked_company   enable row level security;
alter table application       enable row level security;

-- --- app_user -------------------------------------------------------------

-- Always your own row: the app reads it on every request to learn your role,
-- and the policies below would deadlock on themselves without it.
create policy app_user_self_select on app_user
  for select using (id = auth.uid());

create policy app_user_team_select on app_user
  for select using (
    app_role() = 'super_admin'
    or created_by_id = auth.uid()
    or id = app_team_id()
  );

create policy app_user_self_update on app_user
  for update using (id = auth.uid()) with check (
    id = auth.uid()
    -- Your own row, but not your own role: self-promotion to admin would make
    -- the hierarchy decorative.
    --
    -- Compared against app_role() rather than a subquery on app_user — a
    -- subquery here would re-enter this table's own policies and recurse.
    and role = app_role()
  );

-- --- candidate_profile ----------------------------------------------------

create policy candidate_profile_select on candidate_profile
  for select using (
    team_id = app_team_id()
    and (app_role() <> 'bidder' or bidder_visible or created_by = auth.uid())
  );

create policy candidate_profile_insert on candidate_profile
  for insert with check (
    team_id = app_team_id() and created_by = auth.uid()
  );

create policy candidate_profile_update on candidate_profile
  for update using (team_id = app_team_id())
  with check (team_id = app_team_id());

create policy candidate_profile_delete on candidate_profile
  for delete using (
    team_id = app_team_id()
    and (app_role() <> 'bidder' or created_by = auth.uid())
  );

-- --- resume_document ------------------------------------------------------

create policy resume_document_select on resume_document
  for select using (
    team_id = app_team_id()
    and (app_role() <> 'bidder' or created_by = auth.uid())
  );

create policy resume_document_insert on resume_document
  for insert with check (
    team_id = app_team_id() and created_by = auth.uid()
  );

create policy resume_document_update on resume_document
  for update using (
    team_id = app_team_id()
    and (app_role() <> 'bidder' or created_by = auth.uid())
  ) with check (team_id = app_team_id());

create policy resume_document_delete on resume_document
  for delete using (
    team_id = app_team_id()
    and (app_role() <> 'bidder' or created_by = auth.uid())
  );

-- --- resume_file ----------------------------------------------------------
-- Team-wide: the CV library is a small reusable set, and hiding a teammate's
-- upload would just get it re-uploaded.

create policy resume_file_select on resume_file
  for select using (team_id = app_team_id());

create policy resume_file_insert on resume_file
  for insert with check (
    team_id = app_team_id() and created_by = auth.uid()
  );

create policy resume_file_update on resume_file
  for update using (team_id = app_team_id())
  with check (team_id = app_team_id());

create policy resume_file_delete on resume_file
  for delete using (
    team_id = app_team_id()
    and (app_role() <> 'bidder' or created_by = auth.uid())
  );

-- --- blocked_company ------------------------------------------------------
-- Readable by the whole team: a bidder must be able to check the list before
-- applying, which is the only reason it exists.

create policy blocked_company_select on blocked_company
  for select using (team_id = app_team_id());

create policy blocked_company_insert on blocked_company
  for insert with check (
    team_id = app_team_id() and created_by = auth.uid()
  );

create policy blocked_company_delete on blocked_company
  for delete using (
    team_id = app_team_id() and app_role() <> 'bidder'
  );

-- --- application ----------------------------------------------------------

create policy application_select on application
  for select using (
    team_id = app_team_id()
    and (app_role() <> 'bidder' or created_by = auth.uid())
  );

create policy application_insert on application
  for insert with check (
    team_id = app_team_id() and created_by = auth.uid()
  );

create policy application_update on application
  for update using (
    team_id = app_team_id()
    and (app_role() <> 'bidder' or created_by = auth.uid())
  ) with check (team_id = app_team_id());

create policy application_delete on application
  for delete using (
    team_id = app_team_id()
    and (app_role() <> 'bidder' or created_by = auth.uid())
  );

-- ===========================================================================
-- Note on file storage
--
-- Uploaded bytes live in UploadThing, not in Supabase Storage, so there is no
-- bucket or storage.objects policy to define here. Access control for a file
-- is the resume_file row that points at it: the row is team-scoped by the
-- policies above, and the app only ever surfaces a file_url it read from a row
-- the caller was allowed to select.
--
-- Worth being clear about the limit of that: an UploadThing file URL is a
-- capability, not a session-checked resource. Anyone holding the URL can fetch
-- it. That matches how the previous project treated CV links, but if resumes
-- ever need to be unguessable-and-revocable, move them behind a route handler
-- that re-checks the row before streaming.
-- ===========================================================================
